// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szewwlytasszwcnnhfhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6ZXd3bHl0YXNzendjbm5oZmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzI0MzksImV4cCI6MjA2NDAwODQzOX0.85fxj6k27k0zl8Mmpns6lIRwK76YwaVrmo3-Lh8LGhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);